name: Build and Deploy Next.js to Firebase hosting

on:
  workflow_dispatch:
  repository_dispatch:
    types: [microcms]
#  push:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - name: Install NPM packages
        run: npm ci
      - name: Build and Export Next.js app
        run: npm run build
        env:
          MICRO_CMS_API_KEY: ${{ secrets.MICRO_CMS_API_KEY }}
          NEXT_PUBLIC_CAL_API_KEY: ${{ secrets.NEXT_PUBLIC_CAL_API_KEY }}
          NEXT_PUBLIC_CAL_ID: ${{ secrets.NEXT_PUBLIC_CAL_ID }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-out
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: create out directory
        run: mkdir out
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-out
          path: ./out
      - name: Display downloaded directory
        run: |
          ls
      - name: deploy to firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NITTC_WINDOR }}'
          projectId: nittc-windor
          channelId: 'live'
